### ISSUE TITLE
Not working, strips right and bottom lines

### ISSUE THREAD

**Issue by Patola** [l0b0/qr2scad#3]
It is not working with my QRCODE PNG. It strips the rightmost and bottom lines. 
![qrcode-patola-makerlinux0](https://cloud.githubusercontent.com/assets/2991620/16841218/917cfada-49ae-11e6-83f0-174dba0905ba.png)

**Comment by Patola** [comment]
Resulting file as .txt so that github accepts it
[qrcode-patola-makerlinux.scad.txt](https://github.com/l0b0/qr2scad/files/365260/qrcode-patola-makerlinux.scad.txt)

**Comment by l0b0** [comment]
I can't reproduce. I ran `python2 ./qr2scad/qr2scad.py < your.png > qr.scad`, added `qr_code();` at the last line, and rendered in OpenSCAD version 2015.03-3:

![qr](https://cloud.githubusercontent.com/assets/168301/23766144/8b1551c0-04fb-11e7-91ed-44d92a9300b5.png)
